name: Run Bats tests

on:
  push:
    branches:
      - '*'    # triggers on push to any branch
  pull_request:
    branches:
      - '*'    # triggers on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats make

      - name: Run tests
        run: make test